### ISSUE TITLE
Runtime Error: cudaErrorInvalidConfiguration in create_from_pcd() – Invalid CUDA Kernel Launch

### ISSUE THREAD

**Issue by talha-sattar** [KovenYu/WonderWorld#25]
**Environment:** 
- GPU: NVIDIA RTX 6000 ADA PCIe (48GB)  
- CUDA: 12.4  
- PyTorch: 2.4.0  
- Dependencies: Installed via Mamba  

**Error Description:**  
The pipeline fails at `create_from_pcd()` in `scene/gaussian_model.py` during the "Loading Training Cameras" stage. The specific error occurs at:  

_dist2 = torch.clamp_min(distCUDA2(torch.from_numpy(np.asarray(pcd.points)).float().cuda()), 0.0000001)_ 

Could you advise on the root cause and potential fixes for this CUDA configuration error?

<img width="1008" height="437" alt="Image" src="https://github.com/user-attachments/assets/c48ceb31-789d-4bcb-9d2a-c854f85a8d0f" />

**Comment by Finemaker3** [comment]
Hi, did you solve this problem?

**Comment by talha-sattar** [comment]
Hi,
hope you are having great day..
Yeah i had resolved..

**Comment by Finemaker3** [comment]
Hi, thanks for your response.
I encountered the same problem as yours, could you please tell me how did you solve it?

**Comment by talha-sattar** [comment]
Hi — it’s been a while. I solved this about a month ago, but I’m a bit
tied up at the moment. Please WhatsApp me on +92 30064233324 and I’ll
remember to share the details/resources with you. Happy to help.

**Comment by talha-sattar** [comment]
Hey,

Try this config, I think that will be enough, and keep gpt = true...

runs_dir: output/real_campus_2
example_name: real_campus_2

seed: 1

# enable guided depth diffusion
depth_conditioning: True

# use gpt to generate scene description
use_gpt: True
debug: True

# depth model and camera/depth parameters
depth_model: marigold
camera_speed: 0.001
fg_depth_range: 0.015
depth_shift: 0.001
sky_hard_depth: 0.02
init_focal_length: 960

# re-generate sky panorama images
gen_sky_image: False
# generate sky point cloud
gen_sky: False

# enable layer-wise generation
gen_layer: False  # Disable temporarily to isolate error
# load previously generated gaussians
load_gen: False

# Parameters to utilize more GPU resources
max_points: 200000  # Reduced to avoid CUDA error
max_floater_ratio: 0.05
batch_size: 50000   # Smaller batches for stability
